version: "0.2"
language: en
ignorePaths:
  - cspell.config.yaml
  - target
dictionaries:
  - computing-acronyms
  - filetypes
  - fullstack
  - git
  - google
  - npm
  - rust
  - softwareTerms
words:
  - accesstoken
  - artifactregistry
  - bunfig
  - docsrs
  - npmjs
  - packslip
  - thiserror
  - unmatch
ignoreWords:
  - creds
  - dacl
  - myorg
  - userprofile
